#!/bin/bash

# echo "MyDirectoryFileLine" | sed -e 's/\([A-Z]\)/-\1/g' -e 'y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/' -e 's/^-//'

# string
fn_camelize(){
	sed -e 's/[_\-]\(.\)/-\1/g' -e 's/^-//' -e 's/\-[aA]/A/g' -e 's/\-[bB]/B/g' -e 's/\-[cC]/C/g' -e 's/\-[dD]/D/g' -e 's/\-[eE]/E/g' -e 's/\-[fF]/F/g' -e 's/\-[gG]/G/g' -e 's/\-[hH]/H/g' -e 's/\-[iI]/I/g' -e 's/\-[jJ]/J/g' -e 's/\-[kK]/K/g' -e 's/\-[lL]/L/g' -e 's/\-[mM]/M/g' -e 's/\-[nN]/N/g' -e 's/\-[oO]/O/g' -e 's/\-[pP]/P/g' -e 's/\-[qQ]/Q/g' -e 's/\-[rR]/R/g' -e 's/\-[sS]/S/g' -e 's/\-[tT]/T/g' -e 's/\-[uU]/U/g' -e 's/\-[vV]/V/g' -e 's/\-[wW]/W/g' -e 's/\-[xX]/X/g' -e 's/\-[yY]/Y/g' -e 's/\-[zZ]/Z/g' <<< $1
}

# string
fn_lower(){
	sed -e 'y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/' <<< $1
}

# string
fn_upper(){
	sed -e 'y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/' <<< $1
}

# separator string
fn_lower_separeted(){
	sed -e 's/[_\-]/'$1'/g' -e 's/\([A-Z]\)/'$1'\1/g' -e 'y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/' -e 's/^'$1'//' <<< $2
}

# string
underscorize(){
	# echo "$1" | sed -e 's/\([A-Z]\)/_\1/g' -e 'y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/' -e 's/^_//'
	if [ $1 ]; then
		fn_lower_separeted '_' $1
	else
		while read data; do
	      	# printf "$data"
			fn_lower_separeted '_' $data
	  	done
	fi
}

# string
hyphenize(){
	# echo "$1" | sed -e 's/\([A-Z]\)/-\1/g' -e 'y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/' -e 's/^-//'
	if [ $1 ]; then
		fn_lower_separeted '-' $1
	else
		while read data; do
	      	# printf "$data"
			fn_lower_separeted '-' $data
	  	done
	fi
}

# string
camelize(){
	if [ $1 ]; then
		fn_camelize $1
	else
		while read data; do
	      	# printf "$data"
			fn_camelize $data
	  	done
	fi
}

# string
lower(){
	if [ $1 ]; then
		fn_lower $1
	else
		while read data; do
	      	# printf "$data"
			fn_lower $data
	  	done
	fi
}

# string
upper(){
	if [ $1 ]; then
		fn_upper $1
	else
		while read data; do
	      	# printf "$data"
			fn_upper $data
	  	done
	fi
}
